packages/validate/__tests__/integration/api/index.js, packages/validate/__tests__/unit/reducers.js, packages/validate/src/lib/constants/index.js, packages/validate/src/lib/factory/add-method.js, packages/validate/src/lib/reducers/index.js, packages/validate/src/lib/validator/index.js
Adds the option to group validation inputs by a data attribute, rather than just by name.
A couple of recent lenus forms have used seperate number inputs for DD/MM/YYYY that the server required to have separate name attributes, however they needed to be validated together as a group with a custom function.
=> Adding option to group items by a data-val-group attribute 

packages/validate/example/src/index.html, packages/validate/example/src/js/index.js, packages/validate/src/lib/dom/index.js, packages/validate/src/lib/factory/group.js
Hi Mick,
When I was using the add/remove groups functionality I was finding that if there were any groups that were removed from validation that had existing errors on them, it was causing the script to error.  
This is adding the clearError function onto the REMOVE_GROUP action, and adding some conditions to the clearError to check for the existence of a group (in case it has been removed by the action).
Let me know if there's a neater way to do this!
=> Clearing any existing errors when a group is removed

packages/cookie-banner/src/lib/factory.js, packages/cookie-banner/src/lib/ui.js
Separate banner listeners from banner rendering to support submit and option buttons being in the consent form
=> Cookie banner > separate initialising listeners from banner rendering

docs/modal.html, packages/toggle/__tests__/integrations.js, packages/toggle/__tests__/unit/broadcast.js, packages/toggle/example/src/js/index.js, packages/toggle/src/lib/constants.js, packages/toggle/src/lib/dom.js
Addresses #155 
- adds custom events for toggle open and toggle close
- event is dispatched on node (the same element that the toggle is initialised on)
- event is set to bubble so listener can be added to node and/or delegated
- events named 'toggle.open' and 'toggle.close', rationale:
- scope event names with component type so events can be extended to other component types without clashes
- dots in event names are cooler than hyphens or underscores
=> Add custom events to toggle

packages/validate/__tests__/integration/validator/required.js, packages/validate/__tests__/unit/validator/utils.js, packages/validate/src/lib/validator/utils.js
Fixes #167 
- trims value when retrieving it from a group prior to validation
- adds tests
=> Trim value from input when acquiring value for validation

packages/validate/README.md, packages/validate/__tests__/integration/api/index.js, packages/validate/__tests__/unit/reducers.js, packages/validate/example/src/index.html, packages/validate/example/src/js/index.js, packages/validate/src/lib/factory/add-method.js, packages/validate/src/lib/reducers/index.js, packages/validate/src/lib/validator/methods.js
Addresses #172 
This PR improves the addMethod API for adding a custom validation group by allowing an array of fields to be passed rather than being constrained by name or data-group attributes of inputs.
This means that validation groups can slice across any combination of inputs and can include fields that are already in other validation groups, which was not previously possible.
=> Validate > create validation group by passing array of fields

packages/validate/src/lib/dom/index.js
Spotted an error in a project this morning where the project required a call to removeGroup() before the form was validated.  
This causes a call to the clearError function, which was assuming the aria-describedby attribute existed.
Updated the function to check for this existence before using the attribute.
=> Check for aria-described by attribute before usage in clear error

packages/validate/__tests__/integration/api/validate/equalto.js, packages/validate/__tests__/integration/api/validate/remote.js, packages/validate/__tests__/integration/validator/custom.js, packages/validate/__tests__/integration/validator/dateISO.js, packages/validate/__tests__/integration/validator/digits.js, packages/validate/__tests__/integration/validator/email.js, packages/validate/__tests__/integration/validator/equalto.js, packages/validate/__tests__/integration/validator/index.js, packages/validate/__tests__/integration/validator/isHidden.js, packages/validate/__tests__/integration/validator/length.js, packages/validate/__tests__/integration/validator/max.js, packages/validate/__tests__/integration/validator/maxlength.js, packages/validate/__tests__/integration/validator/min.js, packages/validate/__tests__/integration/validator/minlength.js, packages/validate/__tests__/integration/validator/number.js, packages/validate/__tests__/integration/validator/range.js, packages/validate/__tests__/integration/validator/regex-pattern.js, packages/validate/__tests__/integration/validator/required.js, packages/validate/__tests__/integration/validator/stringlength.js, packages/validate/__tests__/integration/validator/url.js, packages/validate/src/lib/validator/index.js
Addresses #208 
- adds support for asynchronous custom validators
- makes all validation methods asynchronous so it simplifies the code a little (I think it can be improved even more, especially if we changed to async/await, but I think that's a separate issue across the whole codebase rather than in these couple of functions).
- adds a test or two, and updates a heap of tests that the change broke
=> Async validators

packages/tabs/README.md, packages/tabs/__tests__/unit/init.js, packages/tabs/src/lib/defaults.js, packages/tabs/src/lib/dom.js, packages/tabs/src/lib/factory.js
We were using the tabs script as part of a project to include tabbed content towards the bottom of the page design.
We were finding that the script was auto-focussing on the first tab on page load, which was pulling the keyboard focus to the wrong spot in the content as there was a lot of content above that was skipped.  The page was also visually being scrolled to the bottom so that the tabs were in view.
This PR potentially adds a 'focusOnLoad' option which defaults to true as per the current implementations, but gives the option to set to false if needed and avoid the auto-focus on page-load only.
Let me know what you think, or if you have any thoughts on other solutions!
Cheers,
S
=> Adding focusOnLoad option

packages/toggle/__tests__/accessibility.js, packages/toggle/example/src/js/index.js, packages/toggle/src/lib/defaults.js, packages/toggle/src/lib/dom.js
Makes the use of the hidden attribute optional by adding a 'useHidden' setting.  Defaults to 'false' for backwards compatibility.
=> Making the use of the hidden attribute optional

packages/validate/src/lib/dom/index.js
A couple of times during build I've been asked to debug a form integration, and the root cause has been a missing label/error node for an input that needs validated.
The missing label is of course an AX issue, but most of the time the label is there and during build there's been a simple typo in the for/id or a mis-translation from flats.
Previously this would error out in the console with a 'cannot append to null' error - so I thought it might be handy to catch that and report it, potentially helping someone in another team debug the issue more easily.
=> Adding better error for lack of label on validation check

packages/cookie-banner/src/lib/ui.js
I was implementing a cookie banner this morning which used the pattern suggestion from the library that has the form within the banner.
I was also hoping to use the new showBanner method to bring the banner back up from an iframe placeholder, but found that the showBanner method wasn't displaying the form in the same way that the main init function was.
Is this OK to add as per the PR?
Cheers,
S
=> Initialising form after banner is shown manually

packages/cookie-banner/README.md, packages/cookie-banner/__tests__/utils.js, packages/cookie-banner/src/lib/constants.js, packages/cookie-banner/src/lib/ui.js, packages/cookie-banner/src/lib/utils.js
For #222 
Adds a custom event dispatcher for three events: `banner.show`, `banner.hide`, and `banner.consent` to simplify integration with the toggle component with the banner for our form-in-banner pattern. (It also offers opportunities to de-couple consent-based code from the banner config if we ever needed or wanted to).
Currently in our form-in-cookie banner code we we have to pass a callback to the showBanner function to initialise the toggle in the banner, and there isn't a simple way to clean up the className from the toggle after the banner is dismissed.
Something like
```
//initialise banner
const banner = cookieBanner(config);
//callback to be passed into show banner
const callback = () => {
//check for banner toggle className and reset if it is present (if a user has previously …
```
=> Add events to cookie banner

docs/modal-gallery.html
Discovered whilst using the component that the docs implicitly suggest the returned gallery is an Array, whereas it is an Object.
This causes errors:
- Runtime error as cannot iterate over the returned Object
- Cannot access [gallery] or gallery[0] as both are undefined
Example code updated to show correct usage (per my implimentation)
Also noted that adding the trigger method ought to be protected by a check to see if a gallery exists, otherwise we have a breaking runtime error - can't add a lister to a null object.
Added defensive conditional to example code.
=> #245 Gallery returns an Object not an iterable Array

docs/validate.html, packages/validate/README.md, packages/validate/__tests__/integration/plugins/date.js, packages/validate/example/src/js/index.js, packages/validate/src/lib/plugins/methods/date.js
Addresses issue/enhancement #236 
Also added date in Past.  For dates in the past, Today's date also counts as valid.  This has been allowed in the use cases or acceptance criteria I've seen for this one (DoB) as technically the DoB could be today?  Happy to adjust based on opinion there though!
Also, I've only ever used this in addition to a separate check that a date is valid in the first place.  I guess there would be an argument that for it to be turned into a useful plugin, it should also run the valid date check first, even if that's not explicitly added as a validation method.  What do you think?
=> Addition of date past/future plugins

docs/validate.html, packages/cookie-banner/README.md, packages/cookie-banner/example/src/index.html, packages/cookie-banner/example/src/js/index.js, packages/cookie-banner/src/lib/constants.js, packages/cookie-banner/src/lib/defaults.js, packages/cookie-banner/src/lib/factory.js, packages/cookie-banner/src/lib/reducers.js, packages/cookie-banner/src/lib/ui.js, packages/cookie-banner/src/lib/utils.js
Adds tab trapping to the current cookie banner implementation:
- Sets an option in the settings, defaults to false.
- The trapping needs to know whether or not the banner is using a toggle so that it can also tab into the toggled options.  I've added this as a setting with the class names in the classnames list, but I'm not sure that this is the best way to handle this... so any suggestions are super welcome
- Moved the banner DOM element into the state because it was in use in quite a few places
- I haven't added tests since we can't emulate the keyboard?
Absolutely would be good to compare to the implementation that @Nick-StormID and roll with the best of both worlds!
=> Adding tab trapping to cookie banner

packages/modal-gallery/src/lib/dom.js
I noticed today that in a gallery with two items the next/previous buttons don't show.  I think these should be appended when there is more than one item - but at the moment the code is checking that there is more than two.
=> Show next/previous buttons if there is more than one item (not 2)

packages/textarea/src/index.js
Closes #240 
I was able to replicate this one in the examples, and the culprit seems to be setting the height of the text area to auto - causing the browser to jump.
I gave this a shot without setting the height to auto first, and it seemed to still work fine.  I checked in Chrome, FF, Edge and safari iOS.
I can see that setting the height to auto first is recommended in the blog posts I've found about auto-resizing text areas.  However those all seem to be a good few years old now, so perhaps more modern browsers no longer have that requirement in order to grab an accurate scroll height?
The original fix in the ticket also works though, so if it's better to go with that then I can update!
=> remove auto height setting

packages/cookie-banner/README.md, packages/cookie-banner/__tests__/analytics/index.js, packages/cookie-banner/__tests__/banner/showBanner.js, packages/cookie-banner/__tests__/google-eu-consent/no-eu-consent-config.js, packages/cookie-banner/src/lib/ui.js
Requested by analytics team for cookie banner.  **This is assuming that the performance container is always loaded and only read via GTM.** as per the latest google consent spec.  
_In the olden days, as my son would say, we used to track interactions with the cookie banner into Universal Analytics. There may still be some legacy code in the banner that was for that purpose. We never updated this to GA4 for a number of reasons, but mostly because it used the measurement API. If I recall, Mick looked into it, but I don't remember us ever really using it in GA4._
__However, using Google Consent Mode v2 offers an opportunity to track slightly differently and I'm wondering how much might be involved to send dataLayer events with the following:_
- Banner displays (just an event, no other data) …
=> Adding data layer tracking for cookie banner GCMv2

packages/scroll-points/.npmignore, packages/scroll-points/README.md, packages/scroll-points/__tests__/unit.js, packages/scroll-points/example/src/index.html, packages/scroll-points/example/src/js/index.js, packages/scroll-points/src/lib/defaults.js, packages/scroll-points/src/lib/factory.js
Resolves #287 
- sweep of codebase to elimate dead code, run linting, fix any non-breaking niggles or annoyances
- sweep of docs
- clean-up example
- sweep of tests
- publish src folder to npm
- allow replaying of intersection observer, default false for backwards compat
=> Scroll points v1

packages/scroll-spy/__tests__/index.js, packages/scroll-spy/example/src/index.html, packages/scroll-spy/src/lib/dom.js
When I was setting up Playwright I used the code from the Jest test in the example.html to make sure it had all the scenarios needed for testing.
The JEST markup had an example where the link didn't have a hash to test how this was handled in the initialisation.  When this example was tried in the browser and the browser scrolled - it threw a console error.  This PR is an intermediate one to address that before carrying on with the tests.
=> Fixes console error when initialised with no hash
